### ISSUE TITLE
Cannot build on Linux

### ISSUE THREAD

**Issue by pdurkan** [KjellKod/g3log#59]
Hi,

I'm trying to build the project on Linux by following your readme. Unfortunately its not working. I'm getting the below error.

Thanks

```
[  5%] Building CXX object CMakeFiles/g3logger.dir/src/logworker.cpp.o
In file included from /home/XXX/logging/g3log/src/g3log/sinkhandle.hpp:11:0,
                 from /home/XXX/logging/g3log/src/g3log/logworker.hpp:16,
                 from /home/XXX/logging/g3log/src/logworker.cpp:9:
/home/XXX/logging/g3log/src/g3log/sink.hpp: In instantiation of ‘g3::internal::Sink<T>::Sink(std::unique_ptr<T>, DefaultLogCall) [with DefaultLogCall = void (g3::FileSink::*)(g3::MoveOnCopy<g3::LogMessage>); T = g3::FileSink]’:
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/ext/new_allocator.h:110:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/alloc_traits.h:250:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/alloc_traits.h:387:4:   required from ‘static void std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/shared_ptr_base.h:400:4:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/ext/new_allocator.h:110:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Sp_counted_ptr_inplace<g3::internal::Sink<g3::FileSink>, std::allocator<g3::internal::Sink<g3::FileSink> >, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<g3::internal::Sink<g3::FileSink> >, std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = std::_Sp_counted_ptr_inplace<g3::internal::Sink<g3::FileSink>, std::allocator<g3::internal::Sink<g3::FileSink> >, (__gnu_cxx::_Lock_policy)2u>]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/alloc_traits.h:250:4:   [ skipping 3 instantiation contexts ]
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/shared_ptr_base.h:993:35:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/shared_ptr.h:317:64:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}; _Tp = g3::internal::Sink<g3::FileSink>]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/shared_ptr.h:599:39:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Alloc = std::allocator<g3::internal::Sink<g3::FileSink> >; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}]’
/data/tools/gcc/gcc-4.7.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.7.0/../../../../include/c++/4.7.0/bits/shared_ptr.h:615:42:   required from ‘std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = g3::internal::Sink<g3::FileSink>; _Args = {std::unique_ptr<g3::FileSink, std::default_delete<g3::FileSink> >, void (g3::FileSink::*&)(g3::MoveOnCopy<g3::LogMessage>)}]’
/home/XXX/logging/g3log/src/g3log/logworker.hpp:100:75:   required from ‘std::unique_ptr<g3::SinkHandle<T> > g3::LogWorker::addSink(std::unique_ptr<T>, DefaultLogCall) [with T = g3::FileSink; DefaultLogCall = void (g3::FileSink::*)(g3::MoveOnCopy<g3::LogMessage>)]’
/home/XXX/logging/g3log/src/logworker.cpp:128:102:   required from here
/home/XXX/logging/g3log/src/g3log/sink.hpp:48:84: error: cannot allocate an object of abstract type ‘g3::internal::SinkWrapper’
In file included from /home/XXX/logging/g3log/src/g3log/logworker.hpp:15:0,
                 from /home/XXX/logging/g3log/src/logworker.cpp:9:
/home/XXX/logging/g3log/src/g3log/sinkwrapper.hpp:16:14: note:   because the following virtual functions are pure within ‘g3::internal::SinkWrapper’:
/home/XXX/logging/g3log/src/g3log/sinkwrapper.hpp:18:23: note: 	virtual void g3::internal::SinkWrapper::send(g3::LogMessageMover)
make[2]: *** [CMakeFiles/g3logger.dir/src/logworker.cpp.o] Error 1
make[1]: *** [CMakeFiles/g3logger.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by KjellKod** [comment]
I believe you need at least gcc 4.8

**Comment by KjellKod** [comment]
FYI:

g2log and g2log-dev should work on gcc 4.7.1

**Comment by pdurkan** [comment]
Ok, thanks. We'll try moving to 4.8 or using g2log

**Comment by KjellKod** [comment]
If you can upgrade then gcc 5 is probably even better ;)

Also....  another strong reason to upgrade gcc is that version 4.7.0 had a few very nasty bugs. So if you for some reason have to stay on 4.7 you should at least upgrade to 4.7.2 or 4.7.3

Let me know if you have any more questions. You can always reach me on my email too hedstrom at kjellkod dot cc
